compiler: G:\Steam\steamapps\common\Skyrim\Papyrus Compiler\PapyrusCompiler.exe
flags: TESV_Papyrus_Flags.flg
output: G:\Steam\steamapps\common\Skyrim\Data\Scripts
imports:
    - E:\Users\Infernio\Desktop\Home\Programming\Skyrim\Anofeyn\scripts\source
    - G:\Steam\steamapps\common\Skyrim\Data\Scripts\Source
    - G:\Steam\steamapps\common\Skyrim\Data\Scripts
optimize: true
