compiler: G:\Steam\steamapps\common\Skyrim\Papyrus Compiler\PapyrusCompiler.exe
flags: TESV_Papyrus_Flags.flg
output: C:\Users\Infernio\Desktop\Programming\Skyrim\Anofeyn\scripts
imports:
    - C:\Users\Infernio\Desktop\Programming\Skyrim\Anofeyn\scripts\source
    - C:\Users\Infernio\Desktop\Programming\Skyrim\MLib\scripts\source
    - G:\Steam\steamapps\common\Skyrim\Data\Scripts\Source
    - G:\Steam\steamapps\common\Skyrim\Data\Scripts
optimize: true
